### PR TITLE
Fix: Add MembersReferenceResolved condition for cp groups

### LINKED ISSUE #797: KonnectGatewayControlPlane have no status for CP group members references
## Current Behavior

When creating a CP group like so:

```
echo '
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: control-plane-group
  namespace: default
spec:
  name: control-plane-group # Name used to identify the Gateway Control Plane in Konnect
  cluster_type: CLUSTER_TYPE_CONTROL_PLANE_GROUP # Type of the Gateway Control Plane
  members:
    - name: gateway-control-plane # Reference to the KonnectGatewayControlPlane object
  konnect:
    authRef:
      name: konnect-api-auth # Reference to the KonnectAPIAuthConfiguration object
  ' | kubectl apply -f -
```

there is no status populated to signal whether the reference to the group members was resolved successfully or not.

## Expected Behavior

A conditions is populated for every group member (could be a new `map[name]condition` status field).

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:
Add a `MembersReferenceResolved` condition in status of control plane groups.
**Which issue this PR fixes**

Fixes #797 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: controller/konnect/ops/ops_controlplane.go [hunk 1]
```diff
@@ -145,17 +146,28 @@ func setGroupMembers(
...
+					}
 			}
 			return sdkkonnectcomp.Members{
 				ID: lo.ToPtr(memberCP.GetKonnectID()),
 			}, nil
 		})
 	if err != nil {
+		SetControlPlaneGroupMembersReferenceResolvedConditionFalse(
+			cp,
+			"SomeMemberNotResolved",
```
Comment (pmalek) [inline controller/konnect/ops/ops_controlplane.go]: Can we put this into a named `const` with a comment?

File: controller/konnect/ops/ops_controlplane.go [hunk 2]
```diff
@@ -128,6 +128,7 @@ func setGroupMembers(
 	id string,
 	sdkGroups sdkops.ControlPlaneGroupSDK,
 ) error {
+	// REVIEW: should we add MembersReferenceResolved condition for CP groups with 0 members?
```
Comment (pmalek) [inline controller/konnect/ops/ops_controlplane.go]: I believe we can set this one with a message stating that no members set. Just to be coherent on the API level. WDYT?

**Review by pmalek — COMMENTED** [review]
Can we please cover this with a test? Perhaps we can extend the test cases in https://github.com/Kong/gateway-operator/blob/5d0b4b78c138f606b1eb5116e2649f35cf780bdb/test/envtest/konnect_entities_gatewaycontrolplane_test.go

File: controller/konnect/ops/ops_controlplane.go (hunk 1 above)
Comment (randmonkey) [reply controller/konnect/ops/ops_controlplane.go]: Done.

File: controller/konnect/ops/ops_controlplane.go (hunk 2 above)
Comment (randmonkey) [reply controller/konnect/ops/ops_controlplane.go]: Added a `NoMembers` reason for such case.

**Comment by randmonkey** [comment]
> Can we please cover this with a test? Perhaps we can extend the test cases in https://github.com/Kong/gateway-operator/blob/5d0b4b78c138f606b1eb5116e2649f35cf780bdb/test/envtest/konnect_entities_gatewaycontrolplane_test.go

Added unit tests.

**Review by pmalek — APPROVED** [review]

**Review by pmalek — CHANGES_REQUESTED** [review]
I'm doing some testing on this one and I do not see the condition set consistently. Let's put this on pause until that's resolved.

**Review by pmalek — CHANGES_REQUESTED** [review]
This PR is missing setting the condition when we encounter a conflict against the API. Specifically when we hit https://github.com/Kong/gateway-operator/blob/170469ac707c458f88c97f4c271d71078fa3f353/controller/konnect/ops/ops.go#L118 we have to handle the members there as well (or requeue for update which will handle that, but that's only going to happen when the sync period passes).

**Comment by randmonkey** [comment]
> This PR is missing setting the condition when we encounter a conflict against the API. Specifically when we hit
> 
> https://github.com/Kong/gateway-operator/blob/170469ac707c458f88c97f4c271d71078fa3f353/controller/konnect/ops/ops.go#L118
> 
> we have to handle the members there as well (or requeue for update which will handle that, but that's only going to happen when the sync period passes).

Added `setGroupMembers` in `getControlPlaneForUID`.

File: controller/konnect/ops/ops_controlplane.go [hunk 3]
```diff
@@ -202,5 +232,20 @@ func getControlPlaneForUID(
...
+		// If we failed to set group membership, we should return a specific error with a reason
+		// so the downstream can handle it properly.
+		return id, KonnectEntityCreatedButRelationsFailedError{
+			KonnectID: id,
+			Err:       err,
+			Reason:    konnectv1alpha1.KonnectGatewayControlPlaneProgrammedReasonFailedToSetControlPlaneGroupMembers,
+		}
+	}
+
+	return id, nil
```
Comment (pmalek) [inline controller/konnect/ops/ops_controlplane.go:250]: Do you mind adding a test for this as well? Ideally extending the test suite in https://github.com/Kong/gateway-operator/blob/8c7fbd40e945bb95c5247288131eac3df9cc7113/test/envtest/konnect_entities_gatewaycontrolplane_test.go.

There's already 1 testcase for conflict https://github.com/Kong/gateway-operator/blob/8c7fbd40e945bb95c5247288131eac3df9cc7113/test/envtest/konnect_entities_gatewaycontrolplane_test.go#L375-L450. 1 more for CP group with members would be ideal.

**Review by pmalek — COMMENTED** [review]
Please resolve conflicts that arose since last review.

Overall this looks good. Just 1 nit about adding a test case for this.

File: controller/konnect/ops/ops_controlplane.go (hunk 3 above)
Comment (randmonkey) [reply controller/konnect/ops/ops_controlplane.go:250]: Done.

**Review by pmalek — APPROVED** [review]
