### PR TITLE
fix: fix checking status when using a KonnectGatewayControlPlane with KIC CP type

### LINKED ISSUE #1112: Panic Error - KGO with a KIC cluster type
## Current Behavior

Hi team, when using a KIC CP with the KGO, the CP setup in Konnect is read-only.
A client should normally using the KIC to reconcile CRDs and not able to use KGO.
However if we are creating a `KongService` and set a spec.controlPlaneRef with the KIC CP, KGO is panicking

## Expected Behavior
KGO should not allow and skip trying to reconcile a KongService if cluster type is KIC

## Steps To Reproduce

```
echo '
kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth
  namespace: default
spec:
  type: token
  token: kpat_XXXX
  serverURL: eu.api.konghq.com
' | kubectl apply -f -
```

```
echo '
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: kic-control-plane
  namespace: default
spec:
  name: kic-control-plane # Name used to identify the Gateway Control Plane in Konnect
  cluster_type: CLUSTER_TYPE_K8S_INGRESS_CONTROLLER # Type of the Gateway Control Plane
  konnect:
    authRef:
      name: konnect-api-auth # Reference to the KonnectAPIAuthConfiguration object
  ' | kubectl apply -f -
```

```
echo '
kind: KongService
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: service
  namespace: default
spec:
  name: service
  host: example.com
  controlPlaneRef:
    type: konnectNamespacedRef # This indicates that an in cluster reference is used
    konnectNamespacedRef:
      name: kic-control-plane
  ' | kubectl apply -f -
```

You will get the error:

```
{
  "level": "error",
  "ts": "2025-01-30T19:19:11Z",
  "msg": "Reconciler error",
  "controller": "KongService",
  "controllerGroup": "configuration.konghq.com",
  "controllerKind": "KongService",
  "KongService": {
    "name": "service",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "service",
  "reconcileID": "2c09c878-cb77-4110-969d-331ceef6386e",
  "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:332\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:279\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:240"
}
{
  "level": "error",
  "ts": "2025-01-30T19:19:11Z",
  "logger": "KongService",
  "msg": "operation in Konnect API failed",
  "controller": "KongService",
  "controllerGroup": "configuration.konghq.com",
  "controllerKind": "KongService",
  "KongService": {
    "name": "service",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "service",
  "reconcileID": "cce51d9f-4519-41cf-8132-46dc68aeaca1",
  "op": "create",
  "duration": "18.125µs",
  "error": "can't create KongService default/service without a Konnect ControlPlane ID"
}
{
  "level": "error",
  "ts": "2025-01-30T19:19:11Z",
  "msg": "Observed a panic",
  "controller": "KongService",
  "controllerGroup": "configuration.konghq.com",
  "controllerKind": "KongService",
  "KongService": {
    "name": "service",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "service",
  "reconcileID": "cce51d9f-4519-41cf-8132-46dc68aeaca1",
  "panic": "runtime error: invalid memory address or nil pointer dereference",
  "panicGoValue": "\"invalid memory address or nil pointer dereference\"",
  "stacktrace": "runtime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:900\ngithub.com/kong/gateway-operator/controller/konnect.(*KonnectEntityReconciler[...]).Reconcile\n\t/home/runner/go/pkg/mod/github.com/kong/gateway-operator@v1.4.2/controller/konnect/reconciler_generic.go:512\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:319\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:279\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:240"
}
```

## Operator Version
KGO 1.4

## `kubectl version`
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

Configuring entities in Konnect's ControlPlane of type KIC is not allowed and yields (equivalent `curl`):

```
curl -s -H "Authorization: Bearer ${KONNECT_TOKEN}" --request POST \
  --url https://eu.api.konghq.com/v2/control-planes/c579dfb7-054f-48fd-9ffc-88520236b310/core-entities/services \
  --header 'Content-Type: application/json' \
  --header 'accept: application/json' \
  --data '{"host":"example.internal","id":"49fd316e-c457-481c-9fc7-8079153e4f3c","name":"example-service","path":"/","port":80,"protocol":"http"}' | jq
{
  "code": 7,
  "message": "usage constraint error",
  "details": [
    {
      "@type": "type.googleapis.com/kong.admin.model.v1.ErrorDetail",
      "messages": [
        "operation not permitted on KIC cluster"
      ]
    }
  ]
}

```

This PR

- changes the check in https://github.com/Kong/gateway-operator/pull/1115/files#diff-5b6aadc0fe9b4d0ba8cfd31756eef41ffdcd65687cd077d3b8d427294dcc81b5R525 to verify if the `status` is `nil` before accessing `status.ID`
- changes the comparison in https://github.com/Kong/gateway-operator/pull/1115/files#diff-40d9e12ec4a0bfa12ba2e0a07890b5d034f2d94bf3c1663151dc4a6e539c5358R127 so that only control plane groups are not allowed (this way we get the `ControlPlaneRefValid` condition on an entity set to `true`) but later on when Programmed condition is set we set it to the error returned from the API
  - I'm open to changing this so that an invalid (KIC) cp type would yield a `ControlPlaneRefValid` with status `False` instead (just like we do for group type)
- add 403 SDKError (with message `API error occurred`) to the unrecoverable set of errors

**Which issue this PR fixes**

Fixes  #1112

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

**Review by programmer04 — DISMISSED** [review]

File: controller/konnect/ops/ops_errors.go [hunk 1]
```diff
@@ -130,17 +131,43 @@ func ErrorIsSDKErrorTypeField(err error) bool {
...
+//		]
+//	}
+func ErrorIsSDKError403(err error) bool {
+	var errSDK *sdkkonnecterrs.SDKError
+	if !errors.As(err, &errSDK) {
 		return false
 	}
 
-	return true
+	return errSDK.StatusCode == 403 && errSDK.Message == apiErrorOccurredMessage
```
Comment (czeslavo) [inline controller/konnect/ops/ops_errors.go]: I'm a bit worried about relying on the message content here. I believe the behavior decision should depend only on the status code. I doubt the message content is considered part of the contract from the Konnect perspective, thus it may change in the future and break KGO.

Comment (pmalek) [reply controller/konnect/ops/ops_errors.go]: Good call out. Removed checking the message in https://github.com/Kong/gateway-operator/pull/1115/commits/0b42677d9ea3cef736157c0064b5eb11095d4f32 and added tests.

**Review by programmer04 — DISMISSED** [review]

**Review by czeslavo — DISMISSED** [review]

**Review by czeslavo — APPROVED** [review]
