### PR TITLE
fix: do not reconcile gateways with unsupported gw class

### LINKED ISSUE #586: Finalizers are added to Gateways not belonging to KGO
## Current Behavior

If you create a Gateway that references a GatewayClass different from the one managed by KGO, the finalizers get attached to the Gateway, before exiting from the Gateway reconciliation loop.

## Expected Behavior

If a `Gateway` references a `GatewayClass` not managed by KGO, no KGO reconciliation should be triggered at all on that`Gateway`.

### PR DESCRIPTION
**Pull request by czeslavo**
**What this PR does / why we need it**:

Ensures that if the `Gateway` does not refer to a supported `GatewayClass` (we can successfully get it and verify the `ControllerName` matches the KGO's one), we won't reconcile it and mark it with the Gateway finalizers. 

**Which issue this PR fixes**

Fixes https://github.com/Kong/gateway-operator/issues/586.

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: controller/gateway/controller_watch.go [hunk 1]
```diff
@@ -226,23 +228,25 @@ func (r *Reconciler) listManagedGatewaysInNamespace(ctx context.Context, obj cli
...
 
-		var gatewaClass gatewayv1.GatewayClass
-		if err := r.Client.Get(ctx, objKey, &gatewaClass); err != nil {
-			logger.Error(
-				fmt.Errorf("failed to get GatewayClass"),
-				"failed to Get Gateway's GatewayClass",
-				"gatewayClass", objKey.Name, "gateway", gateway.Name, "namespace", gateway.Namespace,
-			)
+		_, err := gatewayclass.Get(ctx, r.Client, string(gateway.Spec.GatewayClassName))
+		if err != nil {
```
Comment (programmer04) [inline controller/gateway/controller_watch.go]:
```suggestion
		if _, err := gatewayclass.Get(ctx, r.Client, string(gateway.Spec.GatewayClassName)); err != nil {
```

File: internal/errors/errors.go [hunk 2]
```diff
@@ -16,14 +17,19 @@ var ErrUnexpectedObject = errors.New("unexpected object type provided")
...
 
-// ErrTooManyDataPlaneNetworkPolicies is an error which indicates that a DataPlane
-// has too many NetworkPolicies configured.
-var ErrTooManyDataPlaneNetworkPolicies = errors.New("too many data plane network policies")
+func NewErrUnsupportedGateway(reason string) ErrUnsupportedGatewayClass {
+	return ErrUnsupportedGatewayClass{reason: reason}
+}
+
+func (e ErrUnsupportedGatewayClass) Error() string {
+	return fmt.Errorf("unsupported gateway class: %s", e.reason).Error()
```
Comment (programmer04) [inline internal/errors/errors.go]:
```suggestion
	return fmt.Sprintf("unsupported gateway class: %s", e.reason)
```

**Review by pmalek — APPROVED** [review]
