### PR TITLE
fix: data race for setting `cfssl` logger

### LINKED ISSUE #1683: Data race accessing `cfssl` logger from `secrets.EnsureCertificate` and `controlplane.(*Reconciler).generateClientCert()`
### Problem statement

A data race has been discovered in conformance tests run https://github.com/Kong/gateway-operator/actions/runs/15275035937/job/42959284075?pr=1681

```
==================
WARNING: DATA RACE
Write at 0x00000acb8210 by goroutine 1928:
  github.com/cloudflare/cfssl/log.SetLogger()
      /home/runner/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.5/log/log.go:62 +0x30
  github.com/kong/gateway-operator/controller/pkg/secrets.EnsureCertificate[go.shape.*github.com/kong/kubernetes-configuration/api/gateway-operator/v1beta1.DataPlane].setCALogger.func1()
      /home/runner/work/gateway-operator/gateway-operator/controller/pkg/secrets/cert.go:72 +0x73
  sync.(*Once).doSlow()
      /opt/hostedtoolcache/go/1.24.2/x64/src/sync/once.go:78 +0xe1
  sync.(*Once).Do()
      /opt/hostedtoolcache/go/1.24.2/x64/src/sync/once.go:69 +0x44
  github.com/kong/gateway-operator/controller/pkg/secrets.setCALogger()
      /home/runner/work/gateway-operator/gateway-operator/controller/pkg/secrets/cert.go:71 +0x135
  github.com/kong/gateway-operator/controller/pkg/secrets.EnsureCertificate[go.shape.*github.com/kong/kubernetes-configuration/api/gateway-operator/v1beta1.DataPlane]()
      /home/runner/work/gateway-operator/gateway-operator/controller/pkg/secrets/cert.go:192 +0x72
  github.com/kong/gateway-operator/controller/dataplane.ensureDataPlaneCertificate()
      /home/runner/work/gateway-operator/gateway-operator/controller/dataplane/owned_resources.go:45 +0x3c7
  github.com/kong/gateway-operator/controller/dataplane.(*Reconciler).Reconcile()
      /home/runner/work/gateway-operator/gateway-operator/controller/dataplane/controller.go:146 +0x1028
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Reconcile()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:119 +0x1bd
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).reconcileHandler()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:340 +0x52f
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).processNextWorkItem()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300 +0x3b2
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Start.func2.1()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202 +0xe4

Previous read at 0x00000acb8210 by goroutine 1909:
  github.com/cloudflare/cfssl/log.print()
      /home/runner/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.5/log/log.go:67 +0x68
  github.com/cloudflare/cfssl/log.outputf()
      /home/runner/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.5/log/log.go:89 +0x64
  github.com/cloudflare/cfssl/log.Infof()
      /home/runner/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.5/log/log.go:145 +0x564
  github.com/cloudflare/cfssl/signer/local.(*Signer).sign()
      /home/runner/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.5/signer/local/local.go:222 +0x4dd
  github.com/cloudflare/cfssl/signer/local.(*Signer).Sign()
      /home/runner/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.5/signer/local/local.go:499 +0x1659
  github.com/kong/gateway-operator/controller/controlplane.(*Reconciler).generateClientCert()
      /home/runner/work/gateway-operator/gateway-operator/controller/controlplane/controller.go:428 +0xda4
  github.com/kong/gateway-operator/controller/controlplane.(*Reconciler).Reconcile()
      /home/runner/work/gateway-operator/gateway-operator/controller/controlplane/controller.go:258 +0x1ee4
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Reconcile()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:119 +0x1bd
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).reconcileHandler()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:340 +0x52f
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).processNextWorkItem()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300 +0x3b2
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Start.func2.1()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202 +0xe4

Goroutine 1928 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Start.func2()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:198 +0x494
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Start()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:209 +0x4ef
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[sigs.k8s.io/controller-runtime/pkg/reconcile.Request]).Start()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:148 +0x4a
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/manager/runnable_group.go:226 +0x1bd
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.gowrap1()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/manager/runnable_group.go:229 +0x41

Goroutine 1909 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Start.func2()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:198 +0x494
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Start()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:209 +0x4ef
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[sigs.k8s.io/controller-runtime/pkg/reconcile.Request]).Start()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:148 +0x4a
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/manager/runnable_group.go:226 +0x1bd
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.gowrap1()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/manager/runnable_group.go:229 +0x41
==================
```

This task tracks the fix for this data race or research, trying to figure out if this has real world impact beyond the test suite.

### PR DESCRIPTION
**Pull request by programmer04**
**What this PR does / why we need it**:

Since the logger for the whole controller is explicitly configured in `main` let's do the same for a logger used by `cfssl`, it will avoid datarace and make all loggers set in a single place

**Which issue this PR fixes**

Fixes #1683

### CODE REVIEW

File: controller/pkg/secrets/cert.go [hunk 1]
```diff
@@ -38,6 +36,12 @@ import (
 	operatorv1beta1 "github.com/kong/kubernetes-configuration/api/gateway-operator/v1beta1"
 )
 
+// SetCALogger sets the logger for the CFSSL signer. Call it once at the start
+// of the program to ensure that CFSSL logs are captured by the operator's logger.
+func SetCALogger(logger logr.Logger) {
+	cflog.SetLogger(loggerShim{logger: logger})
```
Comment (pmalek) [inline controller/pkg/secrets/cert.go]: Wouldn't it be better to retain the `sync.Once` wrapper here to prevent these issues in the future?

I agree on moving its call to `main` but just to be on the safe side and prevent troubles in the future I'd re-add the `sync.Once`. WDYT?

Comment (programmer04) [reply controller/pkg/secrets/cert.go]: It seems like a little overkill for me, since we do not have such extra "safety" measures. But it costs basically nothing, so I'm adding it and updating description

**Review by pmalek — APPROVED** [review]
