### PR TITLE
fix(konnect): do not set owner relationship between ControlPlane and its config entities

### LINKED ISSUE #788: Konnect entities: All entities get deleted when referenced ControlPlane gets deleted
## Current Behavior

When a `KonnectGatewayControlPlane` is deleted, the control plane is deleted on the Konnect side and all attached entities (services, routes, consumers, ...) gets deleted as well. Then, all corresponding k8s resources (`KongService`,`KongRoute`,`KongConsumer`,...) gets deleted silently.

## Expected Behavior
Similar to #786,  If cascade deletion is expected, we should add logs to tell that the resource are deleted.

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

**Which issue this PR fixes**

Uses condition reason from : https://github.com/Kong/kubernetes-configuration/pull/261

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: controller/konnect/reconciler_generic.go [hunk 1]
```diff
@@ -174,6 +173,13 @@ func (r *KonnectEntityReconciler[T, TEnt]) Reconcile(
 				}
 			}
 		}
+
+		if res, err := setProgrammedStatusConditionBasedOnOtherConditions(ctx, r.Client, ent); err != nil {
+			return res, err
+		} else if !res.IsZero() {
```
Comment (randmonkey) [inline controller/konnect/reconciler_generic.go]: Here the `Reconcile` returns `ctrl.Result{}, nil` when the returned `res`. Do you think it is simpler to directly return the return values from calling `setProgrammedStatusConditionBasedOnOtherConditions` here, like 
```
return setProgrammedStatusConditionBasedOnOtherConditions(ctx, r.Client, ent)
```
?

Comment (pmalek) [reply controller/konnect/reconciler_generic.go]: 👍 0fe2fbf64511d97dd9ecc96e81da7ca0d0b9784a

File: pkg/utils/kubernetes/status.go [hunk 2]
```diff
@@ -195,7 +195,10 @@ func SetAcceptedConditionOnGateway(resource ConditionsAndListenerConditionsAndGe
 	}
 }
 
-func areAllConditionsHaveTrueStatus(resource ConditionsAware) bool {
+// AreAllConditionsHaveTrueStatus checks if all the conditions on the resource are in the True state.
+// It skips the Programmed condition as that particular condition will be set based on
+// the return value of this function.
+func AreAllConditionsHaveTrueStatus(resource ConditionsAware) bool {
 	for _, condition := range resource.GetConditions() {
 		if condition.Type == string(gatewayv1.GatewayConditionProgrammed) {
```
Comment (randmonkey) [inline pkg/utils/kubernetes/status.go]: The logic is not so intuitive here. I think the criteria to return false should be "Type is not `Programmed` or `Ready` and Status is `False`". So it looks clearer to move the `condition.Type != string(consts.ReadyType)` to
 
```
// Skip check if the condition type is "Programmed" or "Ready"
if condition.Type == string(gatewayv1.GatewayConditionProgrammed) || condition.Type == string(consts.ReadyType) {
    continue
} 
```

**Review by randmonkey — DISMISSED** [review]
Genrally LGTM, but small places can be improved (not related to this PR though).

File: pkg/utils/kubernetes/status.go (hunk 2 above)
Comment (pmalek) [reply pkg/utils/kubernetes/status.go]: Addressed in 00f6973af3a0f6b8f8f6f443609b79d34159432b

**Review by randmonkey — DISMISSED** [review]

**Review by tao12345666333 — DISMISSED** [review]

**Review by tao12345666333 — DISMISSED** [review]

**Review by tao12345666333 — APPROVED** [review]
