### PR TITLE
fix(hybridgateway): return explicit errors for unsupported ParentRef kind/group

### LINKED ISSUE #2920: Hybridgateway: Return specific errors for unsupported ParentRef kind and group
## Current Behavior

The `GetSupportedGatewayForParentRef` function currently returns `nil, nil` when a `ParentRef` has an unsupported kind or group. This makes it ambiguous whether the validation passed or failed, and doesn't provide clear information to callers about why a `ParentRef` was rejected.

## Expected Behavior

The `ParentRef` should be skipped.

## Steps To Reproduce

Create an HTTPRoute with a wrong `kind or group` in a `ParentRef`.

### PR DESCRIPTION
**Pull request by alacuku**
**What this PR does / why we need it**:

Previously, GetSupportedGatewayForParentRef returned (nil, nil) when encountering unsupported ParentRef kinds or API groups, making it ambiguous whether validation passed or failed. This forced callers to guess about the validation outcome.

Changes:
- Add ErrUnsupportedKind and ErrUnsupportedGroup sentinel errors
- Return specific errors instead of (nil, nil) for invalid ParentRefs
- Update error handling in HTTPRoute converter to use switch statement
- Add new error types to all error handling paths
- Update tests to verify new error behavior

This improves error clarity and allows callers to distinguish between:
- Wrong kind/group (not supported by controller)
- Gateway not found (resource doesn't exist)
- GatewayClass not found
- Wrong controller (managed by different controller)

All error checks now use errors.Is() for proper sentinel error handling.

**Which issue this PR fixes**

Fixes #2920 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: controller/hybridgateway/converter/http_route.go [hunk 1]
```diff
@@ -215,9 +215,12 @@ func (c *httpRouteConverter) UpdateRootObjectStatus(ctx context.Context, logger
...
-				errors.Is(err, hybridgatewayerrors.ErrNoGatewayController) ||
-				errors.Is(err, hybridgatewayerrors.ErrNoGatewayFound) {
+			switch {
+			case errors.Is(err, hybridgatewayerrors.ErrNoGatewayClassFound),
+				errors.Is(err, hybridgatewayerrors.ErrNoGatewayController),
+				errors.Is(err, hybridgatewayerrors.ErrNoGatewayFound),
+				errors.Is(err, hybridgatewayerrors.ErrUnsupportedKind),
+				errors.Is(err, hybridgatewayerrors.ErrUnsupportedGroup):
 				// If the gateway is not managed by us or not found we skip setting conditions.
 				log.Debug(logger, "Skipping status update for unsupported or non-existent Gateway", "parentRef", pRef)
```
Comment (sandromodarelli) [inline controller/hybridgateway/converter/http_route.go]: what do you think about adding here which error is causing the skip? it may help users during an investigation

**Review by fgiudici — DISMISSED** [review]
lgtm

**Review by mlavacca — DISMISSED** [review]

**Review by mlavacca — APPROVED** [review]

**Review by sandromodarelli — APPROVED** [review]

**Review by fgiudici — APPROVED** [review]
