### PR TITLE
fix(aigateway): check reference grant aigateway credential

### LINKED ISSUE #1150: `cloudProviderCredentials` in `AIGateway` can reference AI cloud credentials in other namespace without permission
## Current Behavior

The `spec.cloudProviderCredentials` can reference `Secret`s in another namespace as AI cloud credential. Currently the `AIGateway` controller do not check the permission of reference, so users can use AI cloud credentials in other namesapces without permission.

## Expected Behavior

User cannot reference credentials in other namespaces unless granted by `ReferenceGrant`.

## Steps To Reproduce

1. Deploy KGO with AI gateway controller enabled
2. Create a `Secret` with an `openai` key in namespace `ns1` 
3. Create an `AIGateway` in namespace `ns2` referencing the `Secret` in namespace `ns1`
4. a `KongPlugin` that is using the AI cloud credential from secret in `ns1` is created in `ns2`.

## Operator Version
1.4.2

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:
Checks if `AIGateway` using a `Secret` as AI cloud provider credential is allowed by `ReferenceGrant`.
**Which issue this PR fixes**

Fixes #1150

**Special notes for your reviewer**:
This may break the current usage of using `Secret` in the different namespace with `AIGateway`. So I listed it in `Breaking Changes` in the CHANGELOG.
**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: controller/specialized/aigateway_controller_reconciler_owned_resources.go [hunk 1]
```diff
@@ -194,6 +197,15 @@ func (r *AIGatewayReconciler) configurePlugins(
 	if aiGateway.Spec.CloudProviderCredentials.Namespace != nil {
 		credentialSecretNamespace = *aiGateway.Spec.CloudProviderCredentials.Namespace
 	}
+
+	// check if referencing the credential secret is allowed by referencegrants.
+	if !r.secretReferenceAllowedByReferenceGrants(ctx, logger, aiGateway, credentialSecretNamespace, credentialSecretName) {
+		log.Info(logger, "Referencing Secret is not allowed by ReferenceGrants",
+			"secret_namespace", credentialSecretNamespace, "secret_name", credentialSecretName)
+		return false, fmt.Errorf("Referencing Secret %s/%s is not allowed by ReferenceGrants",
```
Comment (czeslavo) [inline controller/specialized/aigateway_controller_reconciler_owned_resources.go]:
```suggestion
		return false, fmt.Errorf("referencing Secret %s/%s is not allowed by ReferenceGrants",
```

File: controller/specialized/aigateway_controller_reconciler_owned_resources.go [hunk 2]
```diff
@@ -194,6 +197,15 @@ func (r *AIGatewayReconciler) configurePlugins(
 	if aiGateway.Spec.CloudProviderCredentials.Namespace != nil {
 		credentialSecretNamespace = *aiGateway.Spec.CloudProviderCredentials.Namespace
 	}
+
+	// check if referencing the credential secret is allowed by referencegrants.
+	if !r.secretReferenceAllowedByReferenceGrants(ctx, logger, aiGateway, credentialSecretNamespace, credentialSecretName) {
+		log.Info(logger, "Referencing Secret is not allowed by ReferenceGrants",
+			"secret_namespace", credentialSecretNamespace, "secret_name", credentialSecretName)
```
Comment (czeslavo) [inline controller/specialized/aigateway_controller_reconciler_owned_resources.go]: Given we're returning the error from here, I don't think a separate `Info` log is needed. The controller runtime will log the error, right?
```suggestion
```

File: pkg/utils/kubernetes/referencegrant.go [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+	// Same namespace is always allowed.
+	if from.Namespace == gatewayv1beta1.Namespace(targetNamespace) {
+		return true, nil
+	}
+	referenceGrantList := gatewayv1beta1.ReferenceGrantList{}
+	namespacedClient := client.NewNamespacedClient(cl, targetNamespace)
+	err := namespacedClient.List(
+		ctx,
+		&referenceGrantList,
+	)
```
Comment (czeslavo) [inline pkg/utils/kubernetes/referencegrant.go]: I believe we could limit the scope of listing by indexing the reference grants by `from` entries. How about leaving a note here that we could improve it?

File: pkg/utils/kubernetes/referencegrant.go [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+	"context"
+
+	"github.com/samber/lo"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+	gatewayv1beta1 "sigs.k8s.io/gateway-api/apis/v1beta1"
+)
+
+// AllowedByReferenceGrants checks if the reference from the input `from` to the object(s)
+// in namespace `targetNamespace` with group, kind, name given in the input `to` is allowed by any ReferenceGrant.
+func AllowedByReferenceGrants(
```
Comment (czeslavo) [inline pkg/utils/kubernetes/referencegrant.go:13]: Please consider reusing this new generic function in https://github.com/Kong/gateway-operator/blob/3d5b5061ad25cba0d261e75bc88a6d75857d0a9d/controller/pkg/secrets/ref/ref.go#L75 to limit logic duplication.

**Review by czeslavo — COMMENTED** [review]
LGTM in general, just some nits 👍

File: pkg/utils/kubernetes/referencegrant.go (hunk 4 above)
Comment (randmonkey) [reply pkg/utils/kubernetes/referencegrant.go:13]: :+1:  I think it would make code clearer and more extensible if we refactor `CheckReferenceGrantForSecret` to call `AllowedByReferenceGrants` here. There will be more usage of checking reference permissions by `ReferenceGrant` between other kinds of resources.

File: controller/specialized/aigateway_controller_reconciler_owned_resources.go (hunk 2 above)
Comment (randmonkey) [reply controller/specialized/aigateway_controller_reconciler_owned_resources.go]: Done.

File: pkg/utils/kubernetes/referencegrant.go (hunk 3 above)
Comment (randmonkey) [reply pkg/utils/kubernetes/referencegrant.go]: Added a `// TODO` comment.

File: controller/pkg/secrets/ref/ref.go [hunk 5]
```diff
@@ -82,44 +84,25 @@ func CheckReferenceGrantForSecret(
...
+			Namespace: gatewayv1.Namespace(fromObj.GetNamespace()),
+		},
+		string(*secretRef.Namespace),
+		gatewayv1beta1.ReferenceGrantTo{
+			Kind: "Secret",
+			Name: lo.ToPtr(secretRef.Name),
+		},
+	)
+	if err != nil {
+		return "", false, fmt.Errorf("Failed to check if Secret  %s/%s is allowed by ReferenceGrants: %w",
```
Comment (czeslavo) [inline controller/pkg/secrets/ref/ref.go]:
```suggestion
		return "", false, fmt.Errorf("failed to check if Secret  %s/%s is allowed by ReferenceGrants: %w",
```

**Review by czeslavo — APPROVED** [review]
