### PR TITLE
fix konnect entities duplicate

### LINKED ISSUE #2587: Kong entities duplicated in Konnect when KongService/KongRoute missing konnect name
## Current Behavior

When a `KongService` or `KongRoute` resource is created without the entity name specified in the `spec` (that is, the field that would map to Konnect entity's name/identifier), the generic reconciler in this operator ends up creating two Konnect entities instead of one.

## Expected Behavior

Only one Konnect entity should be created per Kubernetes resource.

## Steps To Reproduce

1. Create a `KongService` (or `KongRoute`) CR without setting `spec.konnect.name` (or the appropriate konnect name field). Example:

```yaml
apiVersion: configuration.konghq.com/v1alpha1
kind: KongService
metadata:
    name: example-service
    namespace: default
spec:
    controlPlaneRef:
        type: konnectNamespacedRef
        konnectNamespacedRef:
            name: test
    host: example-backend.default.svc.cluster.local
    port: 80
  # note: no konnect.name set here
```

2. Apply the resource to a cluster where the kong-operator is running and connected to Konnect.

3. Observe Konnect dashboard or query Konnect API for created entities.

## Operator Version

main

### PR DESCRIPTION
**Pull request by tao12345666333**
**What this PR does / why we need it**:

**Which issue this PR fixes**

Fixes https://github.com/Kong/kong-operator/issues/2587

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: controller/konnect/ops/ops_kongroute.go [hunk 1]
```diff
@@ -23,6 +23,18 @@ func createRoute(
 		return CantPerformOperationWithoutControlPlaneIDError{Entity: route, Op: CreateOp}
 	}
 
+	if route.Spec.Name == nil || *route.Spec.Name == "" {
+		existingID, err := getKongRouteForUID(ctx, sdk, route)
```
Comment (pmalek) [inline controller/konnect/ops/ops_kongroute.go]: Why do we want to list the existing (in Konnect) entities and use those?

As far as I can see Konnect API for e.g. service creation [API doc](https://developer.konghq.com/api/konnect/control-planes-config/v2/#/operations/create-service) does allow creating a service without a name.

BTW: I'm not sure I understand using the existing route ID here to fill in the Konnect API request. Can you elaborate?

Comment (tao12345666333) [reply controller/konnect/ops/ops_kongroute.go]: @pmalek Yes, the Konnect API allows creating a service without a name.

But when we use this API to create a service, it will create a new resource every time. It's not idempotent.

By querying for existing entities with matching UID tag, we can detect if one was already created and recover its ID, avoiding the duplicate.

Maybe we can try to use [Upsert](https://developer.konghq.com/api/konnect/control-planes-config/v2/#/operations/upsert-service) API, WDYT?

Comment (pmalek) [reply controller/konnect/ops/ops_kongroute.go]: If that would work I believe it would be slightly better (prevents the additional list operation).

Comment (tao12345666333) [reply controller/konnect/ops/ops_kongroute.go]: OK, let me try to use the upsert

**Review by pmalek — APPROVED** [review]
