### PR TITLE
fix: dp deploy can be restart

### LINKED ISSUE #1390: Restarting Dataplane deployment should result in new dataplane pods to be created
## Problem Statement
When we restart Deployment resource created by operator for a DataPlane, restarting it results in new ReplicaSet be created but controller set's it replica count to 0,  thus not let the user restart DataPlane pods in a graceful manner.

## Setup Information
kgo version is 1.4.2

## Replication
- Install kgo 
- create a dataplane
- use  kubectl rollout restart deployment to restart deployment

### PR DESCRIPTION
**Pull request by tao12345666333**
**What this PR does / why we need it**:

**Which issue this PR fixes**

Fixes https://github.com/Kong/gateway-operator/issues/1390

**Special notes for your reviewer**:

My test cases cover the following scenarios:

- Test scaling replicas from 2 to 3.
- Simulate a restart operation.
- Test scaling replicas from 3 to 4.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: test/integration/test_dataplane_scale_subresource.go [hunk 1]
```diff
@@ -105,4 +85,82 @@ func TestDataPlaneScaleSubresource(t *testing.T) {
...
+		// Find the new ReplicaSet (one that wasn't in the original list)
+		for i := range newReplicaSetList.Items {
+			rs := &newReplicaSetList.Items[i]
+			if _, exists := existingRSNames[rs.Name]; !exists {
+				newReplicaSet = rs
+				return true
+			}
+		}
+		return false
+	}, testutils.GatewayReadyTimeLimit, testutils.ObjectUpdateTick, "Failed to find new ReplicaSet after rollout restart")
```
Comment (pmalek) [inline test/integration/test_dataplane_scale_subresource.go]: WDYT about adding a helper func which will for example return a `ReplicaSet` which is newer than the provided `time.Time`? This helper could fail the test (using the provided `*testing.T`) if there's more than 1.

I believe this could improve the readability of this test. This would also prevent the need for `existingRSNames`.

File: test/integration/test_dataplane_scale_subresource.go [hunk 2]
```diff
@@ -105,4 +85,82 @@ func TestDataPlaneScaleSubresource(t *testing.T) {
 
 	t.Log("verifying dataplane scales to 3 replicas")
 	require.Eventually(t, testutils.DataPlaneHasNReadyPods(t, GetCtx(), dataplaneName, clients, 3), testutils.GatewayReadyTimeLimit, testutils.ObjectUpdateTick)
+
+	// Get the current ReplicaSets before restart
+	replicaSetList := &appsv1.ReplicaSetList{}
+	err = clients.MgrClient.List(GetCtx(), replicaSetList,
+		client.InNamespace(namespace.Name),
+		client.MatchingLabels(deployment.Spec.Selector.MatchLabels))
```
Comment (pmalek) [inline test/integration/test_dataplane_scale_subresource.go]: Can we add a test helper like `testutils.GetDataPlaneReplicaSets(dp *operatorv1beta1.DataPlane)` (or similar)?

It could find the provided `DataPlane`'s `Deployment` and then find the `ReplicaSet` using the `ownerReferences` matching the `Deployment`.

(Accepting the proposal in the other comment would make us not need the `existingRSNames` anyway).

File: controller/dataplane/owned_deployment.go [hunk 3]
```diff
@@ -306,17 +306,64 @@ func reconcileDataPlaneDeployment(
...
+		// This is different from our previous approach because the desired deployment
+		// is generated from the DataPlane resource and won't have the restart annotation
+		isRestartOperation := false
+		if existing.Spec.Template.Annotations != nil {
+			_, hasRestartAnnotation := existing.Spec.Template.Annotations["kubectl.kubernetes.io/restartedAt"]
+			if hasRestartAnnotation {
+				isRestartOperation = true
+				log.Debug(logger, "detected restart operation", "isRestartOperation", isRestartOperation)
+			}
+		}
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: Can we extract this into a `func` like: `PodTemplateSpecHasRestartAnnotation()` which could return the annotation value and a `boolean` indicating if it was found?

File: controller/dataplane/owned_deployment.go [hunk 4]
```diff
@@ -306,17 +306,64 @@ func reconcileDataPlaneDeployment(
...
+
+				// Ensure the replica count is maintained
+				if originalReplicas != nil {
+					log.Debug(logger, "preserving original replica count", "replicas", *originalReplicas)
+					existing.Spec.Replicas = originalReplicas
+				}
+
+				updated = true
+			}
+		} else if !cmp.Equal(existing.Spec.Template, desired.Spec.Template, opts...) {
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: I think this could be made slightly more readable my using a comparer option to ignore the restart key (and in the future possibly extended with more keys to ignore).

This can be achieved using something like:

```
package dataplane

import (
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/stretchr/testify/require"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	KeyNameRestart = "kubectl.kubernetes.io/restartedAt"
)

func TestX(t *testing.T) {
	a := corev1.PodTemplateSpec{
		ObjectMeta: metav1.ObjectMeta{
			Annotations: map[string]string{
				"obj":          "state",
				KeyNameRestart: "a",
			},
		},
	}
	b := corev1.PodTemplateSpec{
		ObjectMeta: metav1.ObjectMeta{
			Annotations: map[string]string{
				"obj":          "state",
				KeyNameRestart: "b",
			},
		},
	}
	opts := []cmp.Option{
		cmp.FilterPath(
			func(p cmp.Path) bool {
				return p.String() == "ObjectMeta.Annotations"
			},
			cmp.Comparer(
				func(a map[string]string, b map[string]string) bool {
					// NOTE: maps can be of different lengths because of
					// the restart annotation.

					for k, v := range a {
						if k == KeyNameRestart {
							continue
						}
						if b[k] != v {
							return false
						}
					}

					for k, v := range b {
						if k == KeyNameRestart {
							continue
						}
						if a[k] != v {
							return false
						}
					}

					return true

					// NOTE: Also possible to use maps.Equal but less efficient:
					// a = maps.Clone(a)
					// b = maps.Clone(b)
					// delete(a, KeyName)
					// delete(b, KeyName)
					// return maps.Equal(a, b)
				}),
		),
	}

	require.True(t, cmp.Equal(a, b, opts...))

	t.Logf("map a (should be unchanged): %+v", a.Annotations)
	t.Logf("map b (should be unchanged): %+v", b.Annotations)
}
```

This compare func could be placed in a named function and used here. WDYT?

**Comment by pmalek** [comment]
@tao12345666333 Are you working on addressing the comments from [last review](https://github.com/Kong/gateway-operator/pull/1540#pullrequestreview-2825280163)? Looks like they have not been addressed yet.

**Comment by tao12345666333** [comment]
Yes, I am updating it.

Last time, I found that I missed a situation that would cause it to not scale correctly after a restart.

File: test/integration/test_dataplane_scale_subresource.go (hunk 1 above)
Comment (tao12345666333) [reply test/integration/test_dataplane_scale_subresource.go]: Addressed and removed the `existingRSNames`

File: controller/dataplane/owned_deployment.go (hunk 3 above)
Comment (tao12345666333) [reply controller/dataplane/owned_deployment.go]: Yes, addressed.

File: test/integration/test_dataplane_scale_subresource.go (hunk 2 above)
Comment (tao12345666333) [reply test/integration/test_dataplane_scale_subresource.go]: Great!

File: controller/dataplane/owned_deployment.go [hunk 5]
```diff
@@ -27,6 +29,8 @@ import (
 	operatorv1beta1 "github.com/kong/kubernetes-configuration/api/gateway-operator/v1beta1"
 )
 
+const restartAnnotationKey = "kubectl.kubernetes.io/restartedAt"
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go:37]: Can we add a comment to this `const`? Possibly linking it to a relevant k8s doc page?

File: controller/dataplane/owned_deployment.go [hunk 6]
```diff
@@ -271,6 +275,14 @@ func listOrReduceDataPlaneDeployments(
 	return false, &deployments[0], nil
 }
 
+func podTemplateSpecHasRestartAnnotation(template *corev1.PodTemplateSpec) (bool, string) {
+	if template.Annotations == nil {
+		return false, ""
+	}
+	restartTimeStr, hasRestartAnnotation := template.Annotations[restartAnnotationKey]
+	return hasRestartAnnotation, restartTimeStr
+}
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: Idiomatically in Go, you'd return a value first and then a boolean indicating whether it was found/valid/etc.

```suggestion
func podTemplateSpecHasRestartAnnotation(template *corev1.PodTemplateSpec) (string, bool) {
	if template.Annotations == nil {
		return "", false
	}
	return template.Annotations[restartAnnotationKey]
}
```

File: controller/dataplane/owned_deployment.go [hunk 7]
```diff
@@ -306,17 +318,55 @@ func reconcileDataPlaneDeployment(
...
+					isRestartOperation = true
+					log.Debug(logger, "detected recent restart operation", "isRestartOperation", isRestartOperation, "restartTime", restartTime)
+				} else {
+					log.Debug(logger, "found old restart annotation, not treating as restart", "restartTime", restartTime)
+				}
+			} else {
+				isRestartOperation = true // If we can't parse time, assume it's a restart for safety
+				log.Debug(logger, "detected restart with unparseable timestamp", "timestamp", restartTimeStr)
+			}
+		}
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: Can we encapsulate this whole piece of logic in a separate function to prevent `reconcileDataPlaneDeployment` becoming any bigger and to make it more readable?

File: controller/dataplane/owned_deployment.go [hunk 8]
```diff
@@ -306,17 +318,55 @@ func reconcileDataPlaneDeployment(
...
+		// Check if we have a fresh restart annotation (from the last 5 minutes)
+		// This prevents us from treating all deployments with old restart annotations
+		// as perpetually in a restart state, fixing issue #1390
+		hasRestartAnnotation, restartTimeStr := podTemplateSpecHasRestartAnnotation(&existing.Spec.Template)
+		if hasRestartAnnotation {
+			// Only treat it as a restart if the timestamp is recent (within 5 minutes)
+			restartTime, err := time.Parse(time.RFC3339, restartTimeStr)
+			if err == nil {
+				// Check if restart annotation is less than 5 minutes old
+				if time.Since(restartTime) < 5*time.Minute {
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: How did we establish the 5 min as a threshold here? Was it suggested by the community (other operators do the same?) or it's a reasonable estimate that we believe would work well here?

File: test/integration/test_dataplane_scale_subresource.go [hunk 9]
```diff
@@ -105,4 +85,80 @@ func TestDataPlaneScaleSubresource(t *testing.T) {
...
+		return newReplicaSet.Status.ReadyReplicas == *newReplicaSet.Spec.Replicas
+	}, testutils.GatewayReadyTimeLimit, testutils.ObjectUpdateTick, "New ReplicaSet should have all replicas ready")
+
+	t.Log("verifying dataplane still has 3 ready replicas after rollout")
+	require.Eventually(t, testutils.DataPlaneHasNReadyPods(t, GetCtx(), dataplaneName, clients, 3), testutils.GatewayReadyTimeLimit, testutils.ObjectUpdateTick)
+
+	// Test the specific issue where scaling after restart didn't work properly
+	t.Log("scaling DataPlane to 4 replicas after restart")
+	// Test scaling through the scale subresource
+	t.Log("testing scaling through scale subresource")
```
Comment (pmalek) [inline test/integration/test_dataplane_scale_subresource.go]: This is not technically scaling through the subresource but rather through the `.replicas` spec field, right? If so I'd update the comment here.

File: test/integration/replicaset_helpers.go [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+	operatorv1beta1 "github.com/kong/kubernetes-configuration/api/gateway-operator/v1beta1"
+)
+
+// FindReplicaSetNewerThan finds a ReplicaSet created after or at the specified time.
+// This helper logs detailed information about ReplicaSets found to help
+// with debugging timestamp issues.
+//
+// It will return nil if no ReplicaSet is found, and will log a warning if
+// multiple ReplicaSets are found that were created after or at the specified time.
+// In case of multiple matches, it returns the most recently created one.
```
Comment (pmalek) [inline test/integration/replicaset_helpers.go]: This doesn't seem accurate:

This `func` will fail the test outright when there's more than 1 matching `ReplicaSet` (lines 61-63). 

I think we need to either change the comment or update the implementation.

**Review by pmalek — CHANGES_REQUESTED** [review]

File: controller/dataplane/owned_deployment.go (hunk 8 above)
Comment (tao12345666333) [reply controller/dataplane/owned_deployment.go]: @pmalek In the past, DeploymentController had a configuration to control the synchronization period of resources. However, it was later removed after restructuring and version updates. 

It is similar to the control parameters for namespaces that are still retained today, and is essentially an empirical value.   :smile:  (So I chose the same value here.)

https://github.com/kubernetes/kubernetes/blob/82db38a23c7820b1924d89f458fd368023f3980c/pkg/controller/namespace/config/v1alpha1/defaults.go#L41

File: test/integration/test_dataplane_scale_subresource.go (hunk 9 above)
Comment (tao12345666333) [reply test/integration/test_dataplane_scale_subresource.go]: Yes. I should conduct this test here using `kubectl scale` or through the `scale` API.

File: test/integration/replicaset_helpers.go (hunk 10 above)
Comment (tao12345666333) [reply test/integration/replicaset_helpers.go]: Good catch! I forgot to update the comments after modifying its implementation based on your previous feedback.

File: controller/dataplane/owned_deployment.go (hunk 7 above)
Comment (tao12345666333) [reply controller/dataplane/owned_deployment.go]: Are you only referring to the selected part? Or does it include the overall logic related to restart or scale?

(In fact, some logs here can be removed.)

File: test/integration/test_dataplane_scale_subresource.go (hunk 9 above)
Comment (pmalek) [reply test/integration/test_dataplane_scale_subresource.go]: 👍 Let's do this then.

File: controller/dataplane/owned_deployment.go (hunk 7 above)
Comment (pmalek) [reply controller/dataplane/owned_deployment.go]: The selected part. If possible I think we could also pass the desired spec, explaining  why we need it ( to set the restart annotation if found, to prevent changing it).

File: controller/dataplane/owned_deployment.go (hunk 8 above)
Comment (pmalek) [reply controller/dataplane/owned_deployment.go]: Got it. So I believe we could leave a comment here about the chosen value: something like "We use 5m here as threshold as that correlates with const used by k/k (<PROVIDE LINK HERE>). Restart annotations older than this duration shouldn't cause a reconciliation effect". Or similar.

File: controller/dataplane/owned_deployment.go [hunk 11]
```diff
@@ -271,6 +280,43 @@ func listOrReduceDataPlaneDeployments(
...
+				return true
+			} else {
+				log.Debug(logger, "found old restart annotation, not treating as restart", "restartTime", restartTime)
+			}
+		} else {
+			log.Debug(logger, "detected restart with unparseable timestamp", "timestamp", restartTimeStr)
+			return true // If we can't parse time, assume it's a restart for safety
+		}
+	}
+	return false
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: Can we make the happy path the least indented?

So e.g. 

```
	if !hasRestartAnnotation {
		return false
	}
```

```
	restartTime, err := time.Parse(time.RFC3339, restartTimeStr)
	if err != nil {
		log.Debug(logger, "detected restart with unparseable timestamp", "timestamp", restartTimeStr)
		return true // If we can't parse time, assume it's a restart for safety
	}
	// NOTE: No else clause needed here
	...
```

related: https://maelvls.dev/go-happy-line-of-sight/

File: controller/dataplane/owned_deployment.go [hunk 12]
```diff
@@ -271,6 +280,43 @@ func listOrReduceDataPlaneDeployments(
 	return false, &deployments[0], nil
 }
 
+func podTemplateSpecHasRestartAnnotation(template *corev1.PodTemplateSpec) (string, bool) {
+	if template == nil || template.Annotations == nil {
+		return "", false
+	}
+	return template.Annotations[restartAnnotationKey], template.Annotations[restartAnnotationKey] != ""
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: We should be able to do:

```suggestion
	return template.Annotations[restartAnnotationKey]
```

right?

File: controller/dataplane/owned_deployment.go [hunk 13]
```diff
@@ -306,17 +352,32 @@ func reconcileDataPlaneDeployment(
...
-		// ensure that PodTemplateSpec is up to date
 		if !cmp.Equal(existing.Spec.Template, desired.Spec.Template, opts...) {
+
+			if isRestartOperation {
+				// Preserve the restart annotation
+				if desired.Spec.Template.Annotations == nil {
+					desired.Spec.Template.Annotations = make(map[string]string)
+				}
+				// Get the restart timestamp from the existing template
+				restartTimeStr, _ := podTemplateSpecHasRestartAnnotation(&existing.Spec.Template)
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: To prevent calling `podTemplateSpecHasRestartAnnotation` here again (it's already called inside `isRecentDeploymentRestart`) we could add a return value to `isRecentDeploymentRestart` to return the annotation value if present. WDYT?

File: test/integration/replicaset_helpers.go [hunk 14]
```diff
@@ -0,0 +1,69 @@
...
+)
+
+// FindReplicaSetNewerThan finds a ReplicaSet created after or at the specified time.
+// This helper logs detailed information about ReplicaSets found to help
+// with debugging timestamp issues.
+//
+// It will return nil if no ReplicaSet is found or if there's an error listing ReplicaSets.
+// If multiple ReplicaSets are found that were created after or at the specified time,
+// it will fail the test immediately with t.FailNow().
+// A single matching ReplicaSet is required for the test to proceed.
```
Comment (pmalek) [inline test/integration/replicaset_helpers.go]: Mentioning test here, as in "for the test to proceed" seems a bit unclear as there's no test in this context. I suggest to reword this to:

```suggestion
// It succeed when exactly 1 matching ReplicaSet is found.
```

File: test/integration/replicaset_helpers.go [hunk 15]
```diff
@@ -0,0 +1,69 @@
...
+func FindReplicaSetNewerThan(
```
Comment (pmalek) [inline test/integration/replicaset_helpers.go]:
```suggestion
func FindDataPlaneReplicaSetNewerThan(
```

File: test/integration/dataplane_scale_subresource_test.go [hunk 16]
```diff
@@ -95,14 +89,90 @@ func TestDataPlaneScaleSubresource(t *testing.T) {
...
+		if rs != nil {
+			t.Logf("Found new ReplicaSet %s created at %v", rs.Name, rs.CreationTimestamp)
+			newReplicaSet = rs
+			return true
+		}
+		return false
+	}, testutils.GatewayReadyTimeLimit, testutils.ObjectUpdateTick, "Failed to find new ReplicaSet after rollout restart")
+
+	t.Log("verifying new ReplicaSet has correct replica count")
+	assert.NotNil(t, newReplicaSet, "New ReplicaSet should be created")
```
Comment (pmalek) [inline test/integration/dataplane_scale_subresource_test.go]:
```suggestion
	require.NotNil(t, newReplicaSet, "New ReplicaSet should be created")
```

File: test/integration/dataplane_scale_subresource_test.go [hunk 17]
```diff
@@ -17,6 +22,18 @@ import (
...
 
+// run_kubectl_scale runs the kubectl scale command to test the scale subresource for the DataPlane CRD.
+// It scales the DataPlane resource to the specified number of replicas and returns the output and error.
+func run_kubectl_scale(t *testing.T, namespace, name string, replicas int) (string, error) {
+	t.Helper()
+
+	// Execute kubectl scale command
+	cmd := "kubectl scale --namespace=" + namespace + " dataplane/" + name + " --replicas=" + fmt.Sprint(replicas)
+
+	out, err := exec.Command("sh", "-c", cmd).CombinedOutput()
```
Comment (pmalek) [inline test/integration/dataplane_scale_subresource_test.go]:
```suggestion
	out, err := exec.CommandContext(t.Context(), "sh", "-c", cmd).CombinedOutput()
```

File: test/integration/dataplane_scale_subresource_test.go [hunk 18]
```diff
@@ -17,6 +22,18 @@ import (
 	operatorv1beta1 "github.com/kong/kubernetes-configuration/api/gateway-operator/v1beta1"
 )
 
+// run_kubectl_scale runs the kubectl scale command to test the scale subresource for the DataPlane CRD.
+// It scales the DataPlane resource to the specified number of replicas and returns the output and error.
+func run_kubectl_scale(t *testing.T, namespace, name string, replicas int) (string, error) {
```
Comment (pmalek) [inline test/integration/dataplane_scale_subresource_test.go]:
```suggestion
// runKubectlScale runs the kubectl scale command to test the scale subresource for the DataPlane CRD.
// It scales the DataPlane resource to the specified number of replicas and returns the output and error.
func runKubectlScaleDataPlane(t *testing.T, namespace, name string, replicas int) (string, error) {
```

Also: WDYT about using `types.NamespacedName` to prevent accidental errors from providing name first instead of the namespace?

File: controller/dataplane/owned_deployment.go (hunk 12 above)
Comment (tao12345666333) [reply controller/dataplane/owned_deployment.go]: No, we can't.

When we put it in the return, it can only return one value, which does not match the function's signature.
You can test here: https://go.dev/play/p/DYwwm-re340

Comment (pmalek) [reply controller/dataplane/owned_deployment.go]: TIL. Thanks for checking this.

So it seems we can still do the following to save on the double lookup:

```suggestion
	v, ok := template.Annotations[restartAnnotationKey]
	return v, ok
```

right?

Comment (tao12345666333) [reply controller/dataplane/owned_deployment.go]: @pmalek  I don't think so. Because this function is meant to check for the existence of a restart annotation. If its value is empty `""`, that is not expected,  `v, ok := template.Annotations[restartAnnotationKey]` ok will be `true`.

This will lead to logical anomalies later on (however, I have also added relevant error handling for it; in this case, I will assume it is a restart operation).

File: controller/dataplane/owned_deployment.go (hunk 13 above)
Comment (tao12345666333) [reply controller/dataplane/owned_deployment.go]: Yes, we can avoid the function call here by increasing the return value. Do you have any suggestions regarding the function name?   If the return value is increased, then the name `isRecentDeploymentRestart` will no longer be appropriate.

File: controller/dataplane/owned_deployment.go (hunk 12 above)
Comment (pmalek) [reply controller/dataplane/owned_deployment.go]: I see your concern I'm ok with adding this type of checks but OTOH I believe this is defensive programming. I'm just curious: is `""` possible under normal operating conditions?

Comment (pmalek) [reply controller/dataplane/owned_deployment.go]: If we insist on leaving the check in, then this piece of code can become:

```suggestion
	v, ok := template.Annotations[restartAnnotationKey]
	return v, ok && v != ""
```

File: controller/dataplane/owned_deployment.go (hunk 13 above)
Comment (pmalek) [reply controller/dataplane/owned_deployment.go]: `isRecentDeploymentRestart` I think would do with an appropriate godoc added to it. WDYT?

File: controller/dataplane/owned_deployment.go [hunk 19]
```diff
@@ -271,6 +280,46 @@ func listOrReduceDataPlaneDeployments(
...
+		return "", false
+	}
+	v, ok := template.Annotations[restartAnnotationKey]
+	return v, ok && v != ""
+}
+
+// isRecentDeploymentRestart detects if a deployment is undergoing a recent restart operation.
+// It checks for the presence of the kubectl restart annotation and verifies if it's recent (within 5 minutes).
+// Returns true if a recent restart is detected, false otherwise, along with the restart timestamp if present.
+func isRecentDeploymentRestart(template *corev1.PodTemplateSpec, logger logr.Logger) (bool, string) {
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: Minor nit:

I'd keep the order of the return values to be the same as in other functions: so

```suggestion
func isRecentDeploymentRestart(template *corev1.PodTemplateSpec, logger logr.Logger) (string, bool) {
```

File: controller/dataplane/owned_deployment.go [hunk 20]
```diff
@@ -306,17 +355,31 @@ func reconcileDataPlaneDeployment(
...
 		if !cmp.Equal(existing.Spec.Template, desired.Spec.Template, opts...) {
+
+			if isRestartOperation {
+				// Preserve the restart annotation
+				if desired.Spec.Template.Annotations == nil {
+					desired.Spec.Template.Annotations = make(map[string]string)
+				}
+				// Use the restart timestamp we already retrieved
+				desired.Spec.Template.Annotations[restartAnnotationKey] = restartTimeStr
+			}
```
Comment (pmalek) [inline controller/dataplane/owned_deployment.go]: If we move the log about the found restart annotation in here then we'd be able to call `isRecentDeploymentRestart` in this scope and thus making scope of `isRestartOperation` and `restartTimeStr` that smaller. WDYT?

We'd have to remove logging of `isRestartOperation` from line 411 but I'm OK with that.

**Review by pmalek — COMMENTED** [review]
Minor nits, otherwise this already looks good.

File: controller/dataplane/owned_deployment.go (hunk 20 above)
Comment (tao12345666333) [reply controller/dataplane/owned_deployment.go]: makes sense

**Review by pmalek — APPROVED** [review]

**Comment by tao12345666333** [comment]
Got 502 error from konnect

**Comment by tao12345666333** [comment]
Incident-508 has been resolved.
