### PR TITLE
fix: proper deletion of `KonnectExtension` (and its dependent `Secret`)

### LINKED ISSUE #2414: Deletion of `KonnectExtension` (and its dependent `Secret`) hangs identifiably due to finalizers
## Current Behavior

Deletion of `KonnectExtension` (and its dependent `Secret`) hangs identifiably due to finalizers when it was used with `KonnectGatewayControlPlane`

## Expected Behavior

It should be deleted

## Steps To Reproduce

Configure Konnect credentials

```yml
kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth
  namespace: default
spec:
  type: token
  token: XYZ
  serverURL: us.api.konghq.tech
```

apply something like this 

```yml
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: reproduce-gateway-control-plane
  namespace: default
spec:
  createControlPlaneRequest:
    name: reproduce-gateway-control-plane
  konnect:
    authRef:
      name: konnect-api-auth
---
kind: KonnectExtension
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: my-konnect-config
  namespace: default
spec:
  konnect:
    controlPlane:
      ref:
        type: konnectNamespacedRef
        konnectNamespacedRef:
          name: reproduce-gateway-control-plane
---
apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: dataplane-example
  namespace: default
spec:
  deployment:
    podTemplateSpec:
      spec:
        containers:
        - name: proxy
          image: kong:3.9
  extensions:
  - kind: KonnectExtension
    name: my-konnect-config
    group: konnect.konghq.com
```

With `kubectl apply -f example.yml`, and everything is created as expected (you can verify in Konnect too).

Next, delete this configuration with `kubectl delete -f example.yml`, and it hangs

```
konnectgatewaycontrolplane.konnect.konghq.com "reproduce-gateway-control-plane" deleted from default namespace
konnectextension.konnect.konghq.com "my-konnect-config" deleted from default namespace
dataplane.gateway-operator.konghq.com "dataplane-example" deleted from default namespace
```

`KonnectExtension` has a finalizer set 

```yml
finalizers:
  - gateway.konghq.com/konnect-cleanup
```

and respective `Secret`

```yml
finalizers:
  - gateway.konghq.com/secret-in-use
  - gateway.konghq.com/konnect-cleanup
```

Removing `Secret`'s finalizers allows deletion to proceed and end with success (both `KonnectExtension` and `Secret` are deleted)

## Operator Version

Current main https://github.com/Kong/kong-operator/commit/418e5d6238cb5681a4c0a5f4716268081be5988c

### PR DESCRIPTION
**Pull request by programmer04**
**What this PR does / why we need it**:

Please start with reading issue #2414, which includes reproduction steps and some more context.

The root cause is that when `KonnectGatewayControlPlane` is deleted, `KonnectExtension` can't resolve `KonnectAPIAuthConfiguration` to use it to authenticate to Konnect. The chain of references looks like that

```mermaid
  graph TD;
      KonnectExtension-->KonnectGatewayControlPlane-->KonnectAPIAuthConfiguration;
```

When the "middleman"  `KonnectGatewayControlPlane` is missing during deletion of `KonnectExtension` (that is referencing that `KonnectGatewayControlPlane`), the `KonnectAPIAuthConfiguration` can't be resolved (reconciler can't access Konnect API). This PR ensures that `KonnectExtension` has the latest `KonnectAPIAuthConfiguration` name preserved in its status to use it when  `KonnectGatewayControlPlane` is gone.

It's safe to assume that `KonnectAPIAuthConfiguration` is available, because otherwise KO can't talk to Konnect. There is a dedicated issue to make it bulletproof - do not allow deletion before any dependent resources - [#2353](https://github.com/Kong/kong-operator/issues/2353)

**Which issue this PR fixes**

Fixes #2414

**Special notes for your reviewer**:

- a1e8d654fbc8f8be12853a743fbfbe1b8bd3ec00 introduces a test case that reproduces the bug, which ends with 
   ```
   konnect_extension_test.go:308: Deleting KonnectControlPlane
    konnect_entities_test.go:380: Deleting dc521abd-50d0-4074-be7d-7d0ee9e045a8/cp-521f598b and waiting for it gone
    konnect_entities_test.go:385: Waiting for *v1alpha2.KonnectGatewayControlPlane dc521abd-50d0-4074-be7d-7d0ee9e045a8/cp-521f598b to disappear
    konnect_extension_test.go:310: Deleting KonnectExtension
    konnect_entities_test.go:380: Deleting dc521abd-50d0-4074-be7d-7d0ee9e045a8/konnect-extension-dqx4f and waiting for it gone
    konnect_entities_test.go:385: Waiting for *v1alpha2.KonnectExtension dc521abd-50d0-4074-be7d-7d0ee9e045a8/konnect-extension-dqx4f to disappear
    konnect_entities_test.go:385:
                Error Trace:    /Users/jakub.warczarek@konghq.com/Documents/work/kong-operator/test/helpers/eventually/doesnotexist.go:40
                                                        /opt/homebrew/Cellar/go/1.25.2/libexec/src/runtime/asm_arm64.s:1268
                Error:          Should be true
    konnect_entities_test.go:385:
                Error Trace:    /Users/jakub.warczarek@konghq.com/Documents/work/kong-operator/test/helpers/eventually/doesnotexist.go:37
                                                        /Users/jakub.warczarek@konghq.com/Documents/work/kong-operator/test/integration/konnect_entities_test.go:385
                                                        /Users/jakub.warczarek@konghq.com/Documents/work/kong-operator/test/integration/konnect_extension_test.go:311
                Error:          Condition never satisfied
                Test:           TestKonnectExtension/Konnect_hybrid_ControlPlane_different_order_of_deletion_(KonnectGatewayControlPlane_before_KonnectExtension)
                Messages:       *v1alpha2.KonnectExtension dc521abd-50d0-4074-be7d-7d0ee9e045a8/konnect-extension-dqx4f still exists
   ```
- c9df50accadbdca08a1f0d2fffa9ed7a0a55a069 contains actual fix

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: controller/konnect/ops/ops_errors.go [hunk 1]
```diff
@@ -274,13 +274,16 @@ func SDKErrorIsConflict(sdkError *sdkkonnecterrs.SDKError) bool {
...
+func ErrIsNotFound(err error) bool {
 	var (
 		notFoundError *sdkkonnecterrs.NotFoundError
 		sdkError      *sdkkonnecterrs.SDKError
 	)
 	return errors.As(err, &notFoundError) ||
-		errors.As(err, &sdkError) && sdkError.StatusCode == http.StatusNotFound
+		errors.As(err, &sdkError) && sdkError.StatusCode == http.StatusNotFound ||
+		// Returned by e.g. ListKongDataPlaneClientCertificates(...) for non-existing Control Plane ID.
+		err != nil && err.Error() == "{\"message\":\"Not Found\"}"
```
Comment (pmalek) [inline controller/konnect/ops/ops_errors.go]: To prevent us relying on string comparison (which might be unreliable if the error changes ever so slightly), how about we use a custom type and compare unmarshalled object's `Message` field?

File: controller/konnect/konnectextension_controller.go [hunk 2]
```diff
@@ -265,23 +266,44 @@ func (r *KonnectExtensionReconciler) Reconcile(ctx context.Context, req ctrl.Req
...
+		// Update the controlPlane ID to the value presented in the status by ControlPlane itself.
+		cpID = cp.Status.ID
 	}
 
 	log.Debug(logger, "controlPlane reference validity checked")
 
 	apiAuthRef, err := getKonnectAPIAuthRefNN(ctx, r.Client, &ext)
 	if err != nil {
-		if client.IgnoreNotFound(err) != nil {
+		if k8serrors.IsNotFound(err) {
```
Comment (pmalek) [inline controller/konnect/konnectextension_controller.go]: Can we reverse the logic here to get rid of unnecessary `else` clause?

e.g. 

```suggestion
		if !k8serrors.IsNotFound(err) {
			return ctrl.Result{}, err
		}
```

File: controller/konnect/konnectextension_controller.go [hunk 3]
```diff
@@ -399,8 +420,8 @@ func (r *KonnectExtensionReconciler) Reconcile(ctx context.Context, req ctrl.Req
 	log.Debug(logger, "DataPlane certificate validity checked")
 
 	// get the list of DataPlane client certificates in Konnect
-	dpCertificates, err := ops.ListKongDataPlaneClientCertificates(ctx, sdk.GetDataPlaneCertificatesSDK(), cp.Status.ID)
-	if err != nil {
+	dpCertificates, err := ops.ListKongDataPlaneClientCertificates(ctx, sdk.GetDataPlaneCertificatesSDK(), cpID)
```
Comment (tao12345666333) [inline controller/konnect/konnectextension_controller.go:425]: Should we consider the case where cpID is empty? If cpID=="" then skip the process of ListKongDataPlaneClientCertificates. WDYT?

Comment (programmer04) [reply controller/konnect/konnectextension_controller.go:425]: Good point, but I think it's well covered by lines 268-286. I improved a comment after your suggestion to make it clear that ID is obtained or the object is requeued. I tested manually with `KonnectExtension` not attached to CP, and I can delete it without any hassle

**Review by tao12345666333 — APPROVED** [review]
