### PR TITLE
tests: fix TestGatewayDataPlaneNetworkPolicy

### LINKED ISSUE #184: Flaky test: `TestGatewayDataPlaneNetworkPolicy`
```
2023-04-05T02:06:12Z	DEBUG	dataplane	patching DataPlane status	{"namespace": "7fb894ea-de5c-4cb9-a61a-5b6592495bb5", "name": "853e900e-f002-4c0e-9c19-57c445fb28a6-glwqc", "status": {"conditions":[{"type":"Provisioned","status":"True","lastTransitionTime":"2023-04-05T02:06:12Z","reason":"PodsReady","message":"pods for all Deployments are ready"},{"type":"Ready","status":"False","lastTransitionTime":"2023-04-05T02:06:12Z","reason":"WaitingToBecomeReady","message":"Waiting for the resource to become ready"}],"service":"dataplane-proxy-853e900e-f002-4c0e-9c19-57c445fb28a6-glwqcwlz2w","addresses":[{"type":"IPAddress","value":"172.18.0.101"},{"type":"IPAddress","value":"10.96.211.198"}]}}
2023-04-05T02:06:13Z	DEBUG	gateway	controlplane not ready yet	{"namespace": "7fb894ea-de5c-4cb9-a61a-5b6592495bb5", "name": "853e900e-f002-4c0e-9c19-57c445fb28a6"}
2023-04-05T02:06:13Z	DEBUG	gateway	dataplane not ready yet	{"namespace": "7fb894ea-de5c-4cb9-a61a-5b6592495bb5", "name": "853e900e-f002-4c0e-9c19-57c445fb28a6"}
    gateway_test.go:289: 
        	Error Trace:	/home/runner/work/gateway-operator/gateway-operator/test/integration/gateway_test.go:289
        	Error:      	Condition never satisfied
        	Test:       	TestGatewayDataPlaneNetworkPolicy
2023-04-05T02:06:43Z	DEBUG	signed certificate with serial number 643277976984370437849068167471547243045399466671
2023-04-05T02:06:43Z	ERROR	Reconciler error	{"controller": "dataplane", "controllerGroup": "gateway-operator.konghq.com", "controllerKind": "DataPlane", "DataPlane": {"name":"0648c69e-d323-4f5c-8de8-1c8786c47e4e","namespace":"71d05d07-73ec-4000-82c6-f85db20feab5"}, "namespace": "71d05d07-73ec-4000-82c6-f85db20feab5", "name": "0648c69e-d323-4f5c-8de8-1c8786c47e4e", "reconcileID": "e1c11763-8cdc-45d0-a9c0-f6d16a52079f", "error": "secrets \"dataplane-0648c69e-d323-4f5c-8de8-1c8786c47e4e-\" is forbidden: unable to create new content in namespace 71d05d07-73ec-4000-82c6-f85db20feab5 because it is being terminated"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
2023-04-05T02:06:43Z	DEBUG	signed certificate with serial number 290080392827551695722237620900161319346938562903
```

Failed CI run: https://github.com/Kong/gateway-operator/actions/runs/4614171583/jobs/8156871124?pr=694#step:4:1874

### Action Items

- [ ] identify the source of the flake and resolve it
- [ ] re-enable the temporarily disabled netpol sub test https://github.com/Kong/gateway-operator-archive/pull/1419

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

Attempt at fixing #184.

Apparently `SetEnvValueByName` had an ineffectual assignment and this was possibly the culprit for #184.

Also, the `KONG_PORT_MAPS` was set incorrectly with a space:

```
fmt.Sprintf("80:%d, 443:%d", proxyPort, proxySSLPort),
```

**Which issue this PR fixes**

Fixes #184 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: test/integration/test_gateway.go [hunk 1]
```diff
@@ -940,13 +941,13 @@ func setGatewayConfigurationEnvProxyPort(t *testing.T, gatewayConfiguration *ope
...
 
-	container.Env = SetEnvValueByName(container.Env,
+	container.Env = envs.SetValueByName(container.Env,
 		"KONG_PROXY_LISTEN",
 		fmt.Sprintf("0.0.0.0:%d reuseport backlog=16384, 0.0.0.0:%d http2 ssl reuseport backlog=16384", proxyPort, proxySSLPort),
 	)
-	container.Env = SetEnvValueByName(container.Env,
+	container.Env = envs.SetValueByName(container.Env,
 		"KONG_PORT_MAPS",
-		fmt.Sprintf("80:%d, 443:%d", proxyPort, proxySSLPort),
```
Comment (pmalek) [inline test/integration/test_gateway.go:949]: This seems to be the actual fix

**Review by czeslavo — APPROVED** [review]

File: test/integration/utils.go [hunk 2]
```diff
@@ -131,20 +131,6 @@ func GetEnvValueByName(envs []corev1.EnvVar, name string) string {
...
-		if env.Name == name {
-			env.Value = value
-			return envs
-		}
-	}
-	return append(envs, corev1.EnvVar{
-		Name:  name,
-		Value: value,
-	})
-}
```
Comment (programmer04) [inline test/integration/utils.go:146]: Maybe, worth reporting this case to [ineffassign](https://github.com/gordonklaus/ineffassign). WDYT?
We use it as part of `golanci-lint` and in the ideal world it should catch this

**Review by programmer04 — APPROVED** [review]

File: test/integration/utils.go (hunk 2 above)
Comment (pmalek) [reply test/integration/utils.go:146]: Done https://github.com/gordonklaus/ineffassign/issues/91.

Interestingly enough this is detected by https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/unusedwrite

Comment (programmer04) [reply test/integration/utils.go:146]: 🆒
