### PR TITLE
fix(hybridgateway): handle finalizer cleanup when Gateway/HTTPRoute ownership changes

### LINKED ISSUE #2835: HybridGateway - finalizers are added on not owned `HTTPRoute`s
## Current Behavior

If an `HTTPRoute` points to a `Gateway` that does not exist or does not belong to KO, the `HybridGateway` controllers take ownership of that, regardless, by adding a finalizer.

## Expected Behavior

If an `HTTPRoute` does not reference a `Gateway` managed by KO, KO's controllers should leave it untouched.

### PR DESCRIPTION
**Pull request by alacuku**
**What this PR does / why we need it**:

Add filtering logic to detect and handle Gateway API resources that are no longer managed by this controller, preventing stale finalizers from blocking deletion.

Changes:
- Add shouldProcessObject() to filter objects based on finalizer presence and Gateway references before reconciliation
- Add removeFinalizerIfNotManaged() to clean up finalizers from objects no longer under controller management
- Add referencesSupportedGateway() helper to check if objects reference Gateways managed by this controller
- Update Gateway converter to skip translation when Gateway is not supported
- Add comprehensive unit tests achieving 100% coverage for new functions

This fixes scenarios where:
1. GatewayClass is changed to a different controller
2. HTTPRoute parent refs are updated to reference unsupported Gateways
3. Watch predicates pass objects not meant for this controller

The finalizer is now automatically removed when management responsibility transfers to another controller, ensuring proper resource lifecycle without blocking deletions.

**Which issue this PR fixes**

Fixes #2835 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

File: controller/hybridgateway/controller.go [hunk 1]
```diff
@@ -237,6 +242,18 @@ func (r *HybridGatewayReconciler[t, tPtr]) Reconcile(ctx context.Context, req ct
 		return ctrl.Result{Requeue: true}, nil
 	}
 
+	// Remove finlalizer if it is no longer needed.
```
Comment (mlavacca) [inline controller/hybridgateway/controller.go]:
```suggestion
	// Remove finalizer if it is no longer needed.
```

**Review by mlavacca — DISMISSED** [review]

**Review by mlavacca — DISMISSED** [review]

**Review by mlavacca — APPROVED** [review]
