### PR TITLE
fix: kongRoute orphans handling

### LINKED ISSUE #2468: Orphaned Konnect related resources after deletion of `HTTPRoute`
## Current Behavior

For Hybrid `Gateway`, under some circumstances, deletion of `HttpRoute` leaves leftovers like `KongRoute`s

## Expected Behavior

Everything is deleted robustly, and no orphaned Konnect resources are left in the cluster.

## Steps To Reproduce

**Prepare configuration**

```yaml
kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth
  namespace: default
spec:
  type: token
  token: XYZ
  serverURL: us.api.konghq.tech
```

after

```yml
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v2beta1
metadata:
  name: jw-gwc
  namespace: default
spec:
  konnect:
    authRef:
      name: konnect-api-auth
  dataPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
          - name: proxy
            image: kong/kong-gateway:3.12
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kong-v2beta1
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: jw-gwc
    namespace: default
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: jw-gw
  namespace: default
spec:
  gatewayClassName: kong-v2beta1
  listeners:
  - name: http
    protocol: HTTP
    port: 80
```

Next `HTTPRoute` scenario

```yml
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: registry.k8s.io/e2e-test-images/agnhost:2.40
          command:
            - /agnhost
            - netexec
            - --http-port=8080
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 10m
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-echo
  namespace: default
spec:
  parentRefs:
  - name: jw-gw
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /echo
    backendRefs:
    - name: echo
      kind: Service
      port: 80
```

Configuration is finished - traffic is routed properly after a couple of seconds

**Execute scenario**

See `KongRoute`s

```
kubectl get kongroutes
NAME                                         PROGRAMMED
default-httproute-echo.cp1c3f86f3.1b69eced   True
```

Deletion of `HTTPRoute` `httproute-echo` works, and no orphans are left (and it can be recreated). The above will be empty.

The problem is with a situation where, for such a working configuration, an underlying `KonnectGatewayControlPlane` is deleted.

```
kubectl delete konnectgatewayconfiguration jw-gw-XYZ       
```

After a couple of seconds, reconciliation happens and everything works, but examining `KongRoute` reveals

```
kubectl get kongroutes 
NAME                                         PROGRAMMED
default-httproute-echo.cp1c3f86f3.1b69eced   True
default-httproute-echo.cp6c16b3a8.1b69eced   True
```

 One of them - `default-httproute-echo.cp1c3f86f3.1b69eced ` is orphaned.

Deletion of `HTTPRoute` - `kubectl delete httproutes httproute-echo` leaves

```
NAME                                                                       PROGRAMMED
default-httproute-echo.cp1c3f86f3.1b69eced   True
```

which is bad. The remaining `KongRoute` can't be deleted without manually removing its finalizer.

## Operator Version

Current `main`

### PR DESCRIPTION
**Pull request by mlavacca**
**What this PR does / why we need it**:

This PR handles the case when `KongRoute`s attached to a non-existent `KongService` (yet, configured in Konnect) get deleted. The added logic removes the finalizer from the routes in case they are marked for deletion and the service they refer to does not exist.

**Which issue this PR fixes**

Fixes #2468 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

### CODE REVIEW

**Review by programmer04 — COMMENTED** [review]
Could you enhance `TestGatewayHybridFull` by getting rid of 

https://github.com/Kong/kong-operator/blob/21bb8c8ab0c769236140ec55284be65539471a9a/test/integration/gateway_test.go#L378-L398


It will guarantee that the scenario, which is fixed in this PR, works as expected (otherwise the test won't pass because it will hang on cluster cleanup due to orphaned resources).

File: controller/konnect/reconciler_generic.go [hunk 1]
```diff
@@ -177,8 +177,27 @@ func (r *KonnectEntityReconciler[T, TEnt]) Reconcile(
 	// If a type has a KongService ref, handle it.
 	res, err = handleKongServiceRef(ctx, r.Client, ent)
 	if err != nil {
-		if !errors.As(err, &ReferencedKongServiceIsBeingDeleted{}) {
+		switch {
+		// in case the referenced KongService is being deleted, disregard the error
+		// and continue
```
Comment (programmer04) [inline controller/konnect/reconciler_generic.go]:
```suggestion
		// In case the referenced KongService is being deleted, disregard the error
		// and continue.
```

File: controller/konnect/reconciler_generic.go [hunk 2]
```diff
@@ -177,8 +177,27 @@ func (r *KonnectEntityReconciler[T, TEnt]) Reconcile(
...
+		case errors.As(err, &ReferencedKongServiceIsBeingDeleted{}):
+			log.Info(logger, "referenced KongService is being deleted, proceeding with reconciliation", err.Error())
+		case errors.As(err, &ReferencedObjectDoesNotExist{}):
+			if ent.GetDeletionTimestamp().IsZero() {
+				log.Info(logger, "referenced KongService does not exist, proceeding with reconciliation", err.Error())
+			}
+			if controllerutil.RemoveFinalizer(ent, KonnectCleanupFinalizer) {
+				if err := r.Client.Update(ctx, ent); err != nil {
+					if k8serrors.IsConflict(err) {
+						return ctrl.Result{Requeue: true}, nil
```
Comment (programmer04) [inline controller/konnect/reconciler_generic.go]:
```suggestion
						return ctrl.Result{}, nil
```

Image

WDYT?

Comment (mlavacca) [reply controller/konnect/reconciler_generic.go]: I've put 1 second, as here we really need to requeue. I conflict happens, we still have to remove the finalizer from the entity.

**Review by programmer04 — APPROVED** [review]
